name: CD - Déploiement API Crédit

on:
   push:
    branches:
      - master

jobs:
  tests:
    name: Déploiement en production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      
      - name: Add project to PYTHONPATH 
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
        
      - name: Run tests
        run: poetry run pytest --ignore=Monitoring/test_drift.py --ignore=test_api_unique.py --ignore=send_batch_request.py

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      
      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - run: pip install huggingface_hub

      - name: Deploy to Hugging Face 
        env: 
          HF_TOKEN: ${{ secrets.HF_TOKEN }} 
          repo-id: Diaure/Home_Credit_API
        run: python deploy_to_hf.py